//! Compare Rust compress+encrypt output against Python VW_Flash reference.
//!
//! Requires:
//!   1. `FL_8V0906259K__0003.frf` under ../../../frf/
//!   2. Python reference files in ../../../compare_out/block{1..5}_python.bin
//!      (generated by compare_prepare.py)

use std::collections::HashMap;
use std::path::Path;

use mqb_modules::modules::simos18::S18_FLASH_INFO;
use mqb_modules::{BlockData, FlashInfo};

const FRF_S18_K3: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../frf/FL_8V0906259K__0003.frf"
);

const COMPARE_OUT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../../compare_out");

fn extract_frf_to_bin(frf_path: &str, flash_info: &'static FlashInfo) -> Vec<u8> {
    let raw = mqb_binfile::load_raw_blocks(Path::new(frf_path), flash_info)
        .unwrap_or_else(|e| panic!("Could not load blocks from {frf_path}: {e}"));

    let blocks: HashMap<String, BlockData> = raw
        .into_iter()
        .map(|(num, bytes)| {
            let name = flash_info
                .block_number_to_name(num)
                .unwrap_or("UNKNOWN")
                .to_owned();
            (name.clone(), BlockData::with_name(num, bytes, &name))
        })
        .collect();

    mqb_binfile::bin_from_blocks(&blocks, flash_info)
}

#[test]
fn rust_prepare_matches_python() {
    let flash_info = &S18_FLASH_INFO;
    let bin = extract_frf_to_bin(FRF_S18_K3, flash_info);
    let blocks = mqb_binfile::blocks_from_bytes(&bin, flash_info);

    let compare_dir = Path::new(COMPARE_OUT);
    assert!(
        compare_dir.exists(),
        "Python comparison output not found at {COMPARE_OUT}. Run compare_prepare.py first."
    );

    // Sort blocks by block number for deterministic output
    let mut block_list: Vec<_> = blocks.values().collect();
    block_list.sort_by_key(|b| b.block_number);

    let mut any_failed = false;

    for block in &block_list {
        let block_num = block.block_number;
        let name = flash_info.block_number_to_name(block_num).unwrap_or("?");

        // -- Rust compress --
        let rust_compressed = if block_num < 6 {
            mqb_lzss::encode(&block.block_bytes, mqb_lzss::Padding::AesBlock)
        } else {
            block.block_bytes.clone()
        };

        // -- Load Python compressed (pre-encryption) --
        let python_comp_path = compare_dir.join(format!("block{block_num}_python_compressed.bin"));
        let python_compressed = std::fs::read(&python_comp_path)
            .unwrap_or_else(|_| panic!("Missing {}", python_comp_path.display()));

        println!(
            "Block {block_num} ({name}): input={} rust_comp={} python_comp={}",
            block.block_bytes.len(),
            rust_compressed.len(),
            python_compressed.len()
        );

        // -- Verify decompression (content match, ignoring trailing padding bytes) --
        if block_num < 6 {
            let original_len = block.block_bytes.len();
            let rust_decompressed = mqb_lzss::decode(&rust_compressed);
            let python_decompressed = mqb_lzss::decode(&python_compressed);

            // LZSS has no end-of-stream marker, so the decoder may produce a few
            // extra bytes from trailing padding. Only the first original_len bytes
            // need to match.
            assert!(
                rust_decompressed.len() >= original_len,
                "Block {block_num}: Rust decompressed too short ({} < {original_len})",
                rust_decompressed.len()
            );
            assert_eq!(
                &rust_decompressed[..original_len],
                &block.block_bytes[..],
                "Block {block_num}: Rust compress->decompress content mismatch"
            );

            assert!(
                python_decompressed.len() >= original_len,
                "Block {block_num}: Python decompressed too short ({} < {original_len})",
                python_decompressed.len()
            );
            assert_eq!(
                &python_decompressed[..original_len],
                &block.block_bytes[..],
                "Block {block_num}: Python decompress content mismatch"
            );
            println!("  Decompression: both OK (first {original_len} bytes match)");
        }

        // -- Verify AES encryption is identical when given same input --
        let rust_enc_of_python = flash_info.crypto.encrypt(&python_compressed);
        let python_encrypted =
            std::fs::read(compare_dir.join(format!("block{block_num}_python.bin"))).unwrap();
        if rust_enc_of_python == python_encrypted {
            println!(
                "  AES encrypt(python_compressed): MATCH ({} bytes)",
                python_encrypted.len()
            );
        } else {
            eprintln!("  AES MISMATCH: Rust encrypt of Python compressed data differs from Python encrypted!");
            any_failed = true;
        }

        // -- Compare compressed sizes --
        if rust_compressed.len() != python_compressed.len() {
            println!(
                "  Compression size diff: {} (Rust {}, Python {})",
                rust_compressed.len() as isize - python_compressed.len() as isize,
                rust_compressed.len(),
                python_compressed.len()
            );
            // Save for offline analysis
            std::fs::write(
                compare_dir.join(format!("block{block_num}_rust_compressed.bin")),
                &rust_compressed,
            )
            .unwrap();
        } else if rust_compressed == python_compressed {
            println!("  Compressed output: IDENTICAL");
        } else {
            println!("  Compressed output: same size but different content");
            std::fs::write(
                compare_dir.join(format!("block{block_num}_rust_compressed.bin")),
                &rust_compressed,
            )
            .unwrap();
        }
    }

    assert!(!any_failed, "One or more AES encryption comparisons failed");
}
