//! Full-stack integration test for a Simos18 5-block flash sequence.
//!
//! Uses a fixture captured from a successful Python flash session to validate
//! that the Rust flash pipeline produces the exact same UDS protocol exchange.
//!
//! Two test phases:
//! 1. **Data pipeline comparison**: loads `tune.bin`, applies CBOOT patch +
//!    Simos CRC32 checksum fix (matching the full-flash pipeline), then splits
//!    into blocks, LZSS-compresses and AES-encrypts each block, and compares
//!    the output byte-for-byte against Python VW_Flash reference outputs.
//! 2. **UDS protocol**: runs the 5-block flash sequence against a `.can` fixture
//!    derived from the captured log, validating the complete protocol exchange.
//!
//! Requires:
//! - `full_flash_log/tune.bin` one level above the workspace root
//! - Python reference outputs generated by `python_prepare_blocks.py`
//!   (run: `uv run --with pycryptodome python tests/python_prepare_blocks.py
//!          ../../../../full_flash_log/tune.bin tests/python_output`)

use std::path::{Path, PathBuf};

use mqb_binfile::blocks_from_bytes;
use mqb_checksum::validate_simos_block;
use mqb_flash_uds::flash::{flash_blocks, FlashOptions};
use mqb_flash_uds::prepare_block_for_flash;
use mqb_flash_uds::Interface;
use mqb_modules::modules::simos18::S18_FLASH_INFO;
use mqb_modules::PreparedBlockData;

/// Path to the real firmware binary, relative to the workspace root.
const TUNE_BIN_PATH: &str = "full_flash_log/tune.bin";

/// Resolve the path to `tune.bin` relative to the workspace root
/// (two directories above CARGO_MANIFEST_DIR for crates/mqb-flash-uds/).
fn workspace_root() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(|p| p.parent())
        .and_then(|p| p.parent())
        .expect("could not resolve workspace root")
        .to_owned()
}

fn tune_bin_path() -> PathBuf {
    workspace_root().join(TUNE_BIN_PATH)
}

fn python_output_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/python_output")
}

/// Expected block sizes from S18_FLASH_INFO.block_lengths.
const EXPECTED_BLOCK_SIZES: &[(u8, usize)] = &[
    (1, 0x23E00), // CBOOT
    (2, 0xFFC00), // ASW1
    (3, 0xBFC00), // ASW2
    (4, 0x7FC00), // ASW3
    (5, 0x7FC00), // CAL
];

// ── Stage-by-stage comparison against Python reference ──────────────────────

/// Compare the Rust and Python output at each stage of the pipeline:
///
/// 1. Raw block extraction — byte-for-byte identical.
/// 2. LZSS compression — two valid streams can decompress to the same data, so
///    compare decompressed content and report size differences.
/// 3. AES encryption — byte-for-byte identical given the same compressed input.
///
/// Requires `tests/python_output/` generated by `python_prepare_blocks.py`.
#[test]
fn test_simos18_compare_with_python() {
    let tune_path = tune_bin_path();
    if !tune_path.exists() {
        eprintln!("SKIPPED: tune.bin not found at {}", tune_path.display());
        return;
    }
    let py_dir = python_output_dir();
    if !py_dir.exists() {
        eprintln!(
            "SKIPPED: Python reference outputs not found at {}.\n\
             Generate with: uv run --with pycryptodome python tests/python_prepare_blocks.py \
             ../../../../full_flash_log/tune.bin tests/python_output",
            py_dir.display()
        );
        return;
    }

    // Load the full binary
    let mut bin_data = std::fs::read(&tune_path).expect("failed to read tune.bin");
    assert_eq!(bin_data.len(), S18_FLASH_INFO.binfile_size);

    // ── Apply CBOOT patch (same as full-flash pipeline) ────────────────
    let cboot_num = 1u8;
    let cboot_offset = S18_FLASH_INFO
        .binfile_offset(cboot_num)
        .expect("CBOOT offset");
    let cboot_length = S18_FLASH_INFO
        .block_length(cboot_num)
        .expect("CBOOT length");
    let cboot_end = cboot_offset + cboot_length;
    let patched_cboot = mqb_cboot::patch_cboot(&bin_data[cboot_offset..cboot_end])
        .expect("CBOOT patch should succeed");
    bin_data[cboot_offset..cboot_end].copy_from_slice(&patched_cboot);
    eprintln!("  CBOOT sample-mode patch applied");

    // ── Split into blocks ──────────────────────────────────────────────
    let block_map = blocks_from_bytes(&bin_data, &S18_FLASH_INFO);
    assert_eq!(block_map.len(), 5);

    // ── Fix Simos CRC32 checksums (CBOOT checksum invalidated by patch) ─
    // Uses validate_simos_block which handles CBOOT_TEMP automatically —
    // the same function used by the CLI and GUI production code.
    let mut fixed_blocks: Vec<(u8, String, Vec<u8>)> = Vec::new();
    for &(block_num, _expected_raw_size) in EXPECTED_BLOCK_SIZES {
        let name = S18_FLASH_INFO
            .block_number_to_name(block_num)
            .expect("block name");
        let bd = block_map.get(name).expect("block in map");
        let (state, fixed) =
            validate_simos_block(&S18_FLASH_INFO, &bd.block_bytes, block_num, true);
        eprintln!("  block {block_num} ({name}) checksum: {state:?}");
        fixed_blocks.push((block_num, name.to_string(), fixed.into_owned()));
    }

    let mut any_failed = false;

    for (block_num, name, block_bytes) in &fixed_blocks {
        let block_num = *block_num;
        let expected_raw_size = EXPECTED_BLOCK_SIZES
            .iter()
            .find(|(n, _)| *n == block_num)
            .unwrap()
            .1;

        // ── Stage 1: Raw block bytes (after CBOOT patch + checksum fix) ─
        let py_raw = read_py_file(&py_dir, block_num, "raw");
        assert_eq!(
            block_bytes.len(),
            expected_raw_size,
            "block {name} raw size mismatch"
        );
        assert_eq!(
            block_bytes.len(),
            py_raw.len(),
            "block {name} raw size: Rust {} vs Python {}",
            block_bytes.len(),
            py_raw.len()
        );
        assert_eq!(
            block_bytes.as_slice(),
            py_raw.as_slice(),
            "block {name} raw bytes differ from Python"
        );
        eprintln!("  block {block_num} ({name}) raw: MATCH ({expected_raw_size} bytes)");

        // ── Stage 2: LZSS compression ───────────────────────────────────
        let rust_compressed = mqb_lzss::encode(block_bytes, mqb_lzss::Padding::AesBlock);
        let py_compressed = read_py_file(&py_dir, block_num, "compressed");

        if rust_compressed == py_compressed {
            eprintln!(
                "  block {block_num} ({name}) compressed: IDENTICAL ({} bytes)",
                rust_compressed.len()
            );
        } else if rust_compressed.len() == py_compressed.len() {
            eprintln!(
                "  block {block_num} ({name}) compressed: same size ({}) but different encoding",
                rust_compressed.len()
            );
        } else {
            eprintln!(
                "  block {block_num} ({name}) compressed: Rust={} Python={} (delta={})",
                rust_compressed.len(),
                py_compressed.len(),
                rust_compressed.len() as isize - py_compressed.len() as isize,
            );
        }

        // Both must round-trip back to the original data
        let rust_decompressed = mqb_lzss::decode(&rust_compressed);
        let py_decompressed = mqb_lzss::decode(&py_compressed);
        assert!(
            rust_decompressed.len() >= expected_raw_size,
            "Rust decompress too short"
        );
        assert!(
            py_decompressed.len() >= expected_raw_size,
            "Python decompress too short"
        );
        assert_eq!(
            &rust_decompressed[..expected_raw_size],
            &block_bytes[..],
            "block {name}: Rust compress→decompress content mismatch"
        );
        assert_eq!(
            &py_decompressed[..expected_raw_size],
            &block_bytes[..],
            "block {name}: Python compress→decompress content mismatch"
        );
        eprintln!("  block {block_num} ({name}) decompress round-trip: MATCH");

        // ── Stage 3: AES encryption ─────────────────────────────────────
        // Encrypt the PYTHON compressed output with Rust AES, isolating AES
        // from LZSS.
        let py_encrypted = read_py_file(&py_dir, block_num, "encrypted");
        let rust_enc_of_py_compressed = S18_FLASH_INFO.crypto.encrypt(&py_compressed);

        if rust_enc_of_py_compressed == py_encrypted {
            eprintln!(
                "  block {block_num} ({name}) AES(python_compressed): MATCH ({} bytes)",
                py_encrypted.len()
            );
        } else {
            eprintln!(
                "  block {block_num} ({name}) AES MISMATCH! Rust encrypt of Python \
                 compressed data differs from Python encrypted output."
            );
            // Find first differing byte
            if let Some(pos) = rust_enc_of_py_compressed
                .iter()
                .zip(py_encrypted.iter())
                .position(|(a, b)| a != b)
            {
                eprintln!("    first diff at byte {pos}");
            }
            any_failed = true;
        }

        // Also compare the full Rust pipeline (Rust LZSS + Rust AES)
        let rust_full = prepare_block_for_flash(block_bytes, S18_FLASH_INFO.crypto);
        if rust_full == py_encrypted {
            eprintln!(
                "  block {block_num} ({name}) full pipeline (Rust LZSS+AES): \
                 IDENTICAL to Python"
            );
        } else {
            eprintln!(
                "  block {block_num} ({name}) full pipeline: Rust={} Python={} bytes",
                rust_full.len(),
                py_encrypted.len(),
            );
            // Different (but valid) LZSS output makes AES output differ too.
            // The ECU decompresses after decryption, so the result is the same.
            if rust_compressed != py_compressed {
                eprintln!("    (expected — LZSS encodings differ; both decompress correctly)");
            } else {
                eprintln!("    UNEXPECTED — LZSS is identical but AES output differs!");
                any_failed = true;
            }
        }
    }

    assert!(
        !any_failed,
        "One or more AES encryption comparisons failed — see output above"
    );
}

fn read_py_file(dir: &Path, block_num: u8, stage: &str) -> Vec<u8> {
    let path = dir.join(format!("block_{block_num}_{stage}.bin"));
    std::fs::read(&path).unwrap_or_else(|e| panic!("Could not read {}: {e}", path.display()))
}

// ── UDS protocol test ───────────────────────────────────────────────────────

/// Run the full 5-block UDS flash sequence against the captured fixture.
///
/// Covers extended session → VIN read → precondition check → programming
/// session with SA2 authentication (seed 0xF591323C → key 0x64B92C84) →
/// workshop code write → per block: erase, RequestDownload, TransferData,
/// TransferExit, checksum routine → verify dependencies → hard reset.
///
/// Uses synthetic block data (4093 zero bytes per block) to keep the test fast;
/// the fixture responses are the real hardware captures.
#[tokio::test]
async fn test_simos18_full_flash_protocol() {
    let _ = tracing_subscriber::fmt()
        .with_max_level(tracing::Level::INFO)
        .with_test_writer()
        .try_init();

    let block_names = ["CBOOT", "ASW1", "ASW2", "ASW3", "CAL"];
    let blocks: Vec<PreparedBlockData> = (1..=5u8)
        .zip(block_names.iter())
        .map(|(num, &name)| PreparedBlockData {
            block_number: num,
            block_name: name.to_owned(),
            block_encrypted_bytes: vec![0u8; 4093],
            boxcode: String::new(),
            compression_type: 0x0A,
            encryption_type: 0x0A,
            should_erase: true,
            uds_checksum: S18_FLASH_INFO.block_checksum(num).unwrap_or([0; 4]),
            // The captured fixture announces the real block length, not the
            // length of the 4093-byte synthetic payload.
            announced_length: S18_FLASH_INFO.block_length(num).unwrap() as u32,
        })
        .collect();

    let fixture = PathBuf::from(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/simos18_full_flash.can"
    ));

    let opts = FlashOptions {
        interface: Interface::Fake(fixture),
        workshop_code: [0x26, 0x03, 0x11, 0x1E, 0x20, 0x20, 0x20, 0x20, 0x76],
        patch_cboot: false,
        stmin_override: None,
        progress_tx: None,
    };

    flash_blocks(&S18_FLASH_INFO, blocks, opts)
        .await
        .expect("Simos18 5-block flash sequence should complete without error");
}
